server:
  port: 9003

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-0.eureka:8761/eureka
  
  instance:
    hostname: eureka-0

spring:
  application:
    name: FRONTEND-SERVICE
   