{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.configmap_name }}
data:
  user_name: {{ .Values.backend.env.user_name }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      containers:
      - name: {{ .Values.backend.name }}
        image: {{ .Values.backend.image.repository }}
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.image.port.containerPort }}
        env:
          - name: USER_NAME
            valueFrom: 
              configMapKeyRef:
                name: {{ .Values.backend.configmap_name }}
                key: user_name
{{- end}}
