apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  labels:
    app: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app

  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: praveensaxena/frontend:0.0.1
        imagePullPolicy: "Always"
        ports:
          - containerPort: 9003


---

kind: Service
apiVersion: v1
metadata:
  name:  frontend-app-svc
spec:
  selector:
    app:  frontend-app
  type:  ClusterIP
  ports:
  - name:  frontend-app-port
    port:  80
    targetPort:  9003