apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-server-map
data:
  eureka-server: http://eureka-0.eureka:8761/eureka

---
kind: Service
apiVersion: v1
metadata:
  name:  eureka
  labels:
    app: eureka
spec:
  clusterIP: None
  ports:
  - port: 8761
    name: eurekaserviceport
  selector:
    app: eureka

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  selector:
    matchLabels:
      app: eureka
  serviceName: "eureka"
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: praveensaxena/service-registry:0.0.1
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8761
        env:
          - name: EUREKA_SERVER
            valueFrom: 
              configMapKeyRef:
                name: eureka-server-map
                key: eureka-server
                

---
kind: Service
apiVersion: v1
metadata:
  name:  eureka-lb
  labels:
    app: eureka
spec:
  selector:
    app:  eureka
  type:  NodePort
  ports:
  - name:  eurekalbport
    port:  80
    targetPort:  8761
              
    
        