my:
  name: ${USER_NAME}
server:
  port: 9002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka:8761/eureka
  
  instance:
    preferIpAddress: true
    hostname: eureka-0

spring:
  application:
    name: BACKEND-SERVICE   